# 用户配置
user:
  username: "17396154630" 
  password: "hhhSir012345"
  email: "hhhsir0123@gmail.com"  # 接收通知的邮箱
  partner_name: "王葭泐"  # 伙伴姓名

# 登录配置
login:
  url: "https://ggtypt.cumtb.edu.cn/venue/login"
  max_retry: 3  # 验证码识别失败最大重试次数
  auto_captcha: true  # 是否自动识别验证码
  headless: false  # 是否无头模式

# 预订配置
booking:
  enabled: true  # 是否启用预订模式
  preferred_time_slots:
    - "18:00-19:00"
    - "19:00-20:00"
  booking_date: "2025-12-14" # [绝对抢票日期] 如果设置了抢票日期，优先按照抢票日期抢票
  booking_days_ahead: 2 # [相对抢票日期] 提前几天预订，默认为2，不建议修改

# 轮询配置
polling:
  enabled: true  # 是否启用轮询模式
  polling_date: "2025-12-14"  # 轮询目标日期（格式：YYYY-MM-DD）
  polling_time_slots:
    - "08:00-09:00"
  polling_interval: 300  # 轮询间隔（秒）
  is_auto_booking: true  # 是否自动预订

# 邮件通知配置
email:
  smtp_server: "smtp.qq.com"  # SMTP服务器地址
  smtp_port: 465  # SMTP端口
  sender_email: "1647805407@qq.com"  # 发件人邮箱（与user.email可以相同）
  sender_password: "lzflwseyzqmfcjbb"  # 邮箱授权码（不是登录密码！）
  use_ssl: true  # 是否使用SSL（端口465用true，587用false但会自动TLS）

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/badminton_booker.log"